# This action compiles resume.tex into a pdf file

name: Compile
on:
    push:
        branches: [master]

    workflow_dispatch:

jobs:
    compile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Compile Resume
              uses: xu-cheng/latex-action@v2
              with:
                root_file: WilliamBoyles_Resume.tex
                latexmk_use_xelatex: true

            - name: Push Changes
              run: |
                  git config --global user.name 'wmboyles'
                  git config --global user.email 'wmboyles@users.noreply.github.com'
                  git add -A
                  git commit -m "Compile LaTeX files"
                  git push
